### ISSUE TITLE
algorithm details

### ISSUE THREAD

**Issue by chenkingwen** [charlesCXK/Depth2HHA-python#1]
It's difficult to know the algorithm from code. Could you please give some details about the implementation. Thank you very much!

**Comment by stoneeve415** [comment]
Hi, I also want to understand the process of transferring Depth to HHA, could you give us a description of the process？ Thank you!

**Comment by charlesCXK** [comment]
I am sorry to have delayed so many days.
Actually, my original intention to create this repo was to provide an API of HHA-encoding algorithm in Python, so I rewrite it from MATLAB code directly and may have destroyed the original code structure, which makes it hard for you to understand.
I have added a picture in this repo, it explains the general flow of the algorithm. If you understand Chinese, you can have a look :[pic here](https://github.com/charlesCXK/Depth2HHA-python/blob/master/utils/principle.png).
I recommend you to read the [original paper](https://arxiv.org/pdf/1407.5736.pdf) and the [MATLAB code organized by me](https://github.com/charlesCXK/Depth2HHA) for more details. The MATLAB code is easy to understand if you follow the flow of the code. This picture may only act as an auxiliary tool because the details are not detailed enough in it.

**Comment by charlesCXK** [comment]
@chenkingwen @stoneeve415

**Comment by chenkingwen** [comment]
thank you very much!@charlesCXK
