### ISSUE TITLE
Depth and raw depth image

### ISSUE THREAD

**Issue by mkt1412** [charlesCXK/Depth2HHA-python#3]
Hi,
A short question:
Could you explain what exactly you used for your depth and raw depth images? It seems that the depth image (say, 0.png) looks perfect while the raw depth image (0_raw.png) is a registered depth image from a sensor (Kinect for example) with some depth info lost (black shadow). 

Thank you for your concern.

**Comment by charlesCXK** [comment]
Thanks for your attention in this project. In fact, when I get the depth-value array (suppose it is in 'merters'), I simply multiply it by 10000 and save as '.png'. So when we read the image from '.png' file using the parameter I used in the README.md (D = cv2.imread(os.path.join(root, '0.png'), cv2.COLOR_BGR2GRAY)), divide it with 10000 can get the true depth value.






------------------ 原始邮件 ------------------
发件人: "mkt1412"<notifications@github.com>;
发送时间: 2019年7月26日(星期五) 晚上11:50
收件人: "charlesCXK/Depth2HHA-python"<Depth2HHA-python@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [charlesCXK/Depth2HHA-python] Depth and raw depth image (#3)




Hi,
 Two questions:
  
 
Could you explain what exactly you used for your depth and raw depth images? It seems that the depth image (say, 0.png) looks perfect but the raw depth image (0_raw.png) is a registered depth image from a sensor (Kinect for example) with some depth info lost (black shadow). From my perspective, raw depth data should reflect the true depth value and therefore you may want to store it in .npy or .txt format in order to preserve the original float or double value.
 
 
 
About your code, thank you for presenting such a well-explained code. In the comments, you mentioned that the value of depth and raw depth images must be divided by certain factor to make sure the unit is meter. However, you store your depth images in .png with uint 16, it means you project the depth range to (0, 2^16-1) and  therefore original depth information is lost. In this way, I dont think it is wothwhile to divide pxiel value by 10000 since pixel value no longer represents true depth value.
 
  
Thank you for your concern.

**Comment by charlesCXK** [comment]
> Hi,
> A short question:
> Could you explain what exactly you used for your depth and raw depth images? It seems that the depth image (say, 0.png) looks perfect while the raw depth image (0_raw.png) is a registered depth image from a sensor (Kinect for example) with some depth info lost (black shadow).
> 
> Thank you for your concern.

Raw depth serves as a mask when computing HHA image, which is the same with the raw implementation of s-gupta. You could see in the function `computeNormalsSquareSupport`, the x-y-z value for the area where the depth value is missing is set as NAN. This could result in an accurate HHA image because the completed depth map may have some wrong depth values for the depth-missing areas.

**Comment by jiunyen-ching** [comment]
@mkt1412 just in case you're still interested, in the NYUv2 dataset (.mat file), there are two types of depth images namely `depths` and `rawDepths`. From the documentation,

> depths – HxWxN matrix of in-painted depth maps where H and W are the height and width, respectively and N is the number of images. The values of the depth elements are in meters.

> rawDepths – HxWxN matrix of raw depth maps where H and W are the height and width, respectively, and N is the number of images. These depth maps capture the depth images after they have been projected onto the RGB image plane but before the missing depth values have been filled in. Additionally, the depth non-linearity from the Kinect device has been removed and the values of each depth image are in meters.

Hence, depth image (say, 0.png) looks perfect because it's a processed version of raw depth image where the missing depth values were filled in.
